name: forms
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter  
  carousel_slider: ^4.2.0 
  smooth_page_indicator: ^1.1.0 
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  share_plus: ^11.0.0
  lottie: ^3.3.1
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  geolocator: ^14.0.1
  flutter_native_splash: ^2.4.6
  google_maps_flutter: ^2.12.3
  flutter_cache_manager: ^3.4.1
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.10
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  flutter_map_tile_caching: ^10.1.1
  flutter_map: ^8.1.1
  font_awesome_flutter: ^10.8.0
  fl_chart: ^1.1.1
  googleapis_auth: ^2.0.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:  # <-- This is at the root level
  android: true
  ios: true
  image_path: "assets/images/image.png" # Update with your actual icon path

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/image.png
  android: true
  ios: false
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
