// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbflnU4bn7jQqrsQbw3FCZhkooE3w_S48',
    appId: '1:143611444960:web:4bcc76f707237cbab39a85',
    messagingSenderId: '143611444960',
    projectId: 'farm-to-door-auth',
    authDomain: 'farm-to-door-auth.firebaseapp.com',
    storageBucket: 'farm-to-door-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBieo2GxSPBsYm6uoPqI1akZGvwayMld4s',
    appId: '1:143611444960:android:da8319b8a16a6422b39a85',
    messagingSenderId: '143611444960',
    projectId: 'farm-to-door-auth',
    storageBucket: 'farm-to-door-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYiHIUWLdl0HagF6HwXF4pzGALb3vYyQ',
    appId: '1:143611444960:ios:99684bd5e3a60097b39a85',
    messagingSenderId: '143611444960',
    projectId: 'farm-to-door-auth',
    storageBucket: 'farm-to-door-auth.firebasestorage.app',
    iosBundleId: 'com.example.farm2door',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALYiHIUWLdl0HagF6HwXF4pzGALb3vYyQ',
    appId: '1:143611444960:ios:6d50f741b910983ab39a85',
    messagingSenderId: '143611444960',
    projectId: 'farm-to-door-auth',
    storageBucket: 'farm-to-door-auth.firebasestorage.app',
    iosBundleId: 'com.example.forms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbflnU4bn7jQqrsQbw3FCZhkooE3w_S48',
    appId: '1:143611444960:web:26c5b9583990cb59b39a85',
    messagingSenderId: '143611444960',
    projectId: 'farm-to-door-auth',
    authDomain: 'farm-to-door-auth.firebaseapp.com',
    storageBucket: 'farm-to-door-auth.firebasestorage.app',
  );
}
